# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gather-in' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gather-in
  pod 'Alamofire', '4.9.1'
  pod 'IQKeyboardManager'
  pod 'NotificationBannerSwift'
  pod 'SKActivityIndicatorView'
  pod 'Kingfisher'
  pod 'UITextView+Placeholder'
  pod 'SkeletonView'
  pod 'MOLH'
  pod 'Socket.IO-Client-Swift', '~> 16.0.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
